### ISSUE TITLE
Error while generate module

### ISSUE THREAD

**Issue by Haezal** [zulfajuniadi/laravel-base#5]
Error when trying to make module with multiple column. 

![screen shot 2015-12-27 at 10 26 36 am](https://cloud.githubusercontent.com/assets/1388595/12008642/961c5ecc-ac84-11e5-8382-e9b3c058a4b5.png)

**Comment by Haezal** [comment]
Sorry. my bad. It should inside double quote "<fields>". For example, 

php artisan make:module companies "company_name:Name:string|registration_no:Registration No:string"

**Comment by zulfajuniadi** [comment]
yup.. have to be in quote
